name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          echo "${{ SSH_KEY }}" > key
          chmod 600 key
          ssh -t -i key ubuntu@ec2-3-6-87-221.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
