name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          chmod 600 todo-app.pem
          ssh -t -i "todo-app.pem" ubuntu@ec2-3-6-87-221.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
